////
 * Copyright (C) Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
////
[[efsp-addendum-revisions]]
= Addendum: Process Revisions

[[efsp-addendum-revisions-efsp]]
== Eclipse Foundation Specification Process

To update the EFSP itself:

* The Executive Director convenes a committee (composed primarily, but not exclusively, of representatives from Working Group Specification Committees) and appoints a chairperson;
* The Committee initiates the work, gathers requirements, and authors an updated document;
* The Committee approves final draft by simple majority (lazy consensus);
* The Eclipse Board of Directors approves the final draft by super-majority vote; and
* The update is published for use.

[[efsp-addendum-revisions-wg]]
== Working Group Specification Process

Individual Specification Committees may tailor the process for their unique requirements. To develop their own customization of the EFSP:

* The Specification Committee initiates work, gathers requirements, and authors an updated document;
* The Specification Committee approves final draft by super-majority vote (as defined in the EFSP);
* The Working Group Steering Committee approves final draft by super-majority;
* The EMO(ED) approves final draft; and
* The process is published for use.
