////
 * Copyright (C) Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
////

[[efsp-faq]]
= Frequently Asked Questions

[qanda]
How does the role of the Specification Committee differ from the role of the PMC? ::

The Project Management Committee (PMC) manages the technical governance process, and provides oversight. It ensures that the open source rules of engagement are observed and the Eclipse Development Process (EDP) as a whole is followed. It participates in the Intellectual Property Due Diligence Process to ensure that requests for review are technically sound (for example, to ensure that the use of third-party content makes technical sense). The PMC provides best practices. It tends to work more at the development and technical level.
+
The Specification Committee is responsible for ensuring that the rules and processes outlined by the EFSP are implemented by Specification Projects, that the integrity of the Scope is maintained (e.g. that release plans define changes that are in-scope), that community has been properly consulted, implementation is technical feasible, and that the Specification otherwise remains consistent with the goals of the Working Group.
+
The PMC is in the Project Leadership Chain; the Specification Committee is not. Approvals from both parties are required for Progress and Release Reviews.


If a Specification Project is archived, do the Final Specifications that it previously produced remain valid? ::

Yes. All previously created Final Specifications remain valid. 

What does it mean for a Specification Project to be “under the supervision” of a Specification Committee? ::

A Specification Project effectively belongs to one Working Group. By aligning itself with a particular Working Group, a Specification Project agrees to take direction from the corresponding Specification Committee. 

How does the Specification Committee manage the overall roadmap for the Specification Projects under their supervision? ::

How a Specification Committee manages a roadmap varies based on the nature of the parties involved. The Specification Committee may choose to defer this responsibility to one of the Specification Projects (e.g. a _Platform_ Specification Project). The roadmap itself may take the form of a set of published guidelines or best practices, the implementation of a simultaneous release, or required themes and other elements in Release Plans. Ultimately, the Specification Committee should work with the PMC and the Project Teams to build consensus rather than impose rules.

[[efsp-faq-plan-1]]By what criteria does the specification committee assess a plan? What constitutes an acceptable plan? ::

When reviewing a plan, the question that specification committee members need to answer is whether or not they, would vote to approve the eventual completion of that plan when the project returns to the committee for a release review.
+
Specification committee members have to decide whether or not, for example, themes and plan items described in a plan are something they would actually want to see in an implementation of the specification.
+
A specification committees may opt to make specific requirements for plans (including delivery format). That notwithstanding, how specification committee members vote is left to the discretion of the individual committee members. 

What happens if a Review fails? ::

The party that fails (i.e. denies approval) the review is expected to provide feedback in the event of failure. The Specification Team will engage with the party to determine the correct course of action. That course of action may be to re-engage in the Review at a later date or take some other corrective action. In any case, the Reviews required by the process must be completed successfully to proceed to the next step.

What do I do if I feel that my Review was failed unfairly? ::

Follow the Grievance Handling process defined in the EDP.

How is the association of the artifacts of a particular Specification Version represented? ::

The Specification Committee should provide best practices to Specification Projects, for example, a standard metadata format.

What is the difference between a Specification Version and a Final Specification? ::

A Specification Version is produced by a release cycle, then becomes a Final Specification when it is Ratified (under the Eclipse Foundation Specification License (EFSL)).
+
The intellectual property rights required to build a compatible implementation flow from the Final Specification. That is, in order to be considered a Compatible Implementation and benefit from the intellectual property protections provided by the Eclipse Foundation Specification Agreement, an implementation must be based on a final specification. No claims regarding compatibility may be made for an implementation milestone build or unratified Specification Version.

What types of changes are not appropriate for a Service Release? ::

Changes to method signatures or additions of new methods or behavior (for example) are generally not considered appropriate in a Service Release. A Specification Team should consult with their PMC and Specification Committee to determine precisely what sort of review is required for a particular change.

Are Specification Projects required to implement the Eclipse IP Policy and engage in the Eclipse IP Due Diligence Process? ::

Yes. 

When we transmogrify a specification into a Final Specification, we set the copyright holder on the specification document to the Eclipse Foundation, and make that document available under the Eclipse Foundation Specification License. How do we do this? That is, by what legal mechanism do we have the ability to do this? ::

Eclipse Foundation specifications are composed of many contributions, licensed to the Eclipse Foundation via committer and contributor agreements by various authors who maintain ownership of their contributions. When a Specification Project and its related Specification Committee goes through the process of selecting, coordinating, and arranging all these various contributions into a single and final document, this compilation is protected by U.S. copyright law and the rights in it are is owned by the Eclipse Foundation -- even though the rights in each individual contribution remains owned by its contributor. The Eclipse Foundation can make the document available under the Eclipse Foundation Specification License based on the following grant provided for in the Eclipse Contributor Agreement and the Eclipse Foundation's committer agreements:
+
----
...You grant a non- exclusive, worldwide, perpetual, royalty-free license of all necessary rights under Your copyright in and to Your Contributions (the “Specification Grant”): (a) for the Eclipse Foundation (and its contributors solely as a part of foundation projects) to create, reproduce, prepare derivative works of, publicly display, publicly perform, distribute and sublicense specifications subject to the terms of the then-current Eclipse Foundation Specification License...
----
+
By asserting copyright ownership on the specification documents, the Eclipse Foundation has the ability to protect the specifications in the event that a third party fails to follow the terms of the Eclipse Foundation Specification License.