////
 * Copyright (C) Eclipse Foundation, Inc. and others. 
 * 
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 * 
 * SPDX-License-Identifier: EPL-2.0
////

:efspUrl: https://www.eclipse.org/projects/efsp
:ipPolicyUrl: http://eclipse.org/org/documents/Eclipse_IP_Policy.pdf

[[efsp]]
= Eclipse Foundation Specification Committee Handbook

Version 1.0. DRAFT

toc::[]

The document describes the operation of the {efspUrl}[Eclipse Foundation Specification Process] (EFSP) for optional use by Eclipse Foundation Working Groups.

== Roles

=== Specification Committee

The specification committee is responsible for implementing the Eclipse Foundation Specification Process (EFSP) for all specification projects (as that term is defined by the EFSP) under the purview of the a working group. A working group may, via their charter, assign specification committee responsibilities to another committee.

The Specification Committee is ultimately responsible for ensuring that the Final Specifications produced by the Working Group’s Specification Projects make sense. The definition of “makes sense” varies by Specification Committee Participant, but is generally understood to mean that the Specification can be implemented and that those aspects of the {ipPolicyUrl}[Eclipse Intellectual Property Policy] with regard to Essential Claims are observed. In practical terms, Specification Committee Participants wields power via the ballots that are required to approve key lifecycle events per the EFSP.

The Specification Committee is responsible for producing, publishing and maintaining operational guidance documentation for specification projects. This includes the minimum requirements and process for producing a Final Specification. It also includes operational guidance for running a specifications TCK for the purpose of testing for compatibility.

The Specification Chair (or their delegate) is responsible for initiating ballots, tallying their results, disseminating them to the community, and (when appropriate; e.g., in the case a release review ballot) reporting them to the EMO.

The Specification Committee is also responsible for defining and refining how they implement the EFSP for those Specification Projects under their purview.

==== Project Management Committee

The primary role of the Project Management Committee (PMC) is to ensure that project teams are implementing the Eclipse Development Process. In particular, the PMC monitors project activity to ensure that project teams are operating in an open and transparent manner. The PMC reviews and approves (or vetos) committer elections, first validating that candidate committers have demonstrated sufficient merit.

The PMC is further responsible for ensuring that project teams abiding by the Eclipse IP Policy and implementing the IP Due Diligence process. In practical terms, the PMC approves intellectual property contributions (CQs) and provides (limited) guidance to project teams regarding intellectual property (deferring to the Eclipse IP Team as necessary).

The PMC is responsible for the structure of the Top Level Project and the organization of the open source (software and Specification) projects contained within.

The PMC is a link in the project leadership chain. As such, the PMC has a role in the grievance handling process: they identify and document project dysfunction (with the responsibility to remove/replace/add disruptive committers).

The PMC provides other oversight regarding the operation of open source projects. They review and approve release and progress review materials, and facilitate cross-project communication within the Top-Level Project.

=== Project Lead(s)

The lead is responsible for initiating reviews as the project reaches the appropriate milestone.

=== Participant Representative

The EFSP states that a _member participant_ may appoint a representative committer. A member participant is defined as an Eclipse Foundation solutions, enterprise, or strategic member of the Eclipse Foundation. This specifically excludes committer members. This makes sense as, to be a committer member participant (the EFSP refers to this an an _individual participant_) in a working group, one must already be a committer. This does mean, however, that an individual participant who is a committer on one specification project cannot appoint themselves as a participant representative on another. 

The intention of a participant representative is to ensure continuity of a member participant's interest. That is, this is a power that a member participant will use to ensure that they have at least one committer on the project to ensure the continued flow of intellectual property grants. If the member participant already has an employee as a committer, then that member participant is considered to already have a participant representative and cannot appoint another.

== Reviews

Specification projects in active development must engage in a progress or release review at least once per year. In practical terms, this means that the clock starts ticking when the plan review that occurs at the beginning of the development cycle concludes successfully, and is reset following a successful progress review.

The entire process is halted when either the specification project engages in a successful release review (thereby concluding the development cycle), or the specification team decides to abandon the cycle.

[NOTE]
====
The EMO schedules reviews to conclude on the first and third Wednesday of the month; this will impact the timing of the start of a specification committee vote and the timing of a project team re-engaging following a failed vote. This means that specification committee chair must start the ballot with enough time to conclude the voting period one week prior to the either the first or third Wednesday of the month if they wish to minimize the time for the review to complete. In the event that the specification committee opts to extend a vote, the EMO will, at its discretion, either bump the corresponding review to the next review slot or withhold approval of the review until the results of the specification committee vote are received.
====



The PMC approval and the specification committee vote are different things. We solicit and handle them separately.

The primary role of the PMC is to ensure that project teams are implementing the EDP. In particular, the PMC monitors project activity to ensure that project teams are operating in an open and transparent manner. 

The specification committee is ultimately responsible for ensuring that the ratified final specifications produced by the working group’s specification projects match the working group’s purpose and goals, that they can be implemented, and that those aspects of the Eclipse Intellectual Property Policy with regard to essential claims are observed. 

=== Creation Reviews

==== Creation Review Ballot

___
Your vote is required to approve the creation of the `<specification>` Project with the following scope:

`<details>`

Per the Eclipse Foundation Specification Process, this will be a `<duration>` ballot, ending on `<date>`. We require a super-majority positive vote of the Specification Committee representatives. 

While only Specification Committee representatives votes will be binding, all are welcome and encouraged to participate.  

Specification committee representatives, your vote is hereby requested. Please respond with pass:[+1] (positive), pass:[+0] (abstain), or pass:[-1] (reject).  Any feedback that you can provide to support your vote will be appreciated.
____

=== Plan Reviews

Plan reviews are not formally tracked or managed by the EMO.

A plan review requires a <<efsp-operations-ballot,ballot>> of the specification committee.

When reviewing a plan, the question that specification committee members need to ask is whether or not they would vote to approve the eventual completion of the plan when the project returns for a release review. If the answer is yes, then the specification committee member should vote in the affirmative `pass:[+1]`; they should either vote in the negative `pass:[-1]` or abstain `pass:[+0]` otherwise.

The basis upon which this decision is made is at the discretion of the individual specification committee member. The specification committee may decide to establish a set of guidelines or requirements to provide a basis for voting; though these may instead be regarded as a gate to even starting a ballot

Ideally, when casting their vote, specification committee members should focus less on the mechanics of implementing the plan and more on the broader implications of the themes and changes suggested in the plan to implementers, adopters, and the ecosystem. 

=== Progress Reviews

=== Release Reviews

Releases of specification projects operate under the Eclipse Foundation Development Process (EDP) augmented by the Eclipse Foundation Specification Process (EFSP).

From the EMO's POV, before a release review will be declared successful, we need:

1) IP Log approved by the IP Team;
2) Release and corresponding review materials approved by the PMC; and
3) Specifications approved by the specification committee.

These approvals can be sought in an order or in parallel.

It is up to the individual parties to determine the basis on which they will approve.

Minimally... the EMO needs the PMC's approval to mean that--to the best of their know


[[efsp-operations-ballot]]
== Ballots

Run in the specification committee's public mailing list.

Starts with a call for a ballot, inviting specification committee members to indicate their vote in the affirmative with a `pass:[+1]`, the negative with `pass:[-1]` or their decision to abstain with `pass:[+0]`.

Specification committee members vote on behalf of their constituency (generally the company whose interests they represent on the committee, or--in the case of an elected representative--their electoral base).

____
Your vote is required to approve and ratify the release of `<specification>`.

The Eclipse Foundation Specification Process (EFSP) requires a successful ballot of the specification committee in order to ratify the products of this release as a Final Specification (as that term is defined in the EFSP).

`<details>`

Per the process, this will be a `<duration>` day ballot, ending on `<date>` that requires a super-majority positive vote of the `<working-group>` specification committee members (note that there is no veto). Community input is welcome, but only votes cast by specification committee representatives will be counted.

Specification committee representatives, your vote is hereby requested. Please respond with pass:[+1] (positive), pass:[+0] (abstain), or pass:[-1] (reject).  Any feedback that you can provide to support your vote will be appreciated.
____

== Converting Existing Projects

Restructuring Review. Specialization of the creation and plan review.

____
We need to restructure the existing `<project>` into a specification project as defined by the Eclipse Foundation Specification Process (EFSP). For this, the EMO has initiated a restructuring review.

The purpose of a restructuring review is to change the nature of a project. While we are not strictly creating a new project, we are in a manner of thinking, creating a new specification project from an existing project. With this in mind, we are treating this as a creation review from the perspective of the specification committee approval requirement.

Per the process, this will be a `<duration>` day ballot, ending on `<date>` that requires a super-majority positive vote of the `<working-group>` specification committee members (note that there is no veto). Community input is welcome, but only votes cast by specification committee representatives will be counted.

`<details>`

Specification committee representatives, your vote is hereby requested. Please respond with pass:[+1] (positive), pass:[+0] (abstain), or pass:[-1] (reject).  Any feedback that you can provide to support your vote will be appreciated.
____


The `<details>` should concisely describe the changes that are proposed. This could be as simple as a statement stating that "The Eclipse Foo project will be converted into a specification project.", but other changes may be included.

For example:

____
We will rename "Eclipse Project for JTA" project to "Jakarta Transactions" and convert it into a specification project with this project/specification scope statement:

Jakarta Transactions defines a standard that allows the demarcation of transactions and the transactional coordination of XA-aware resource managers as described in the X/Open XA-specification and mapped to the Java SE XAResource interface within Java applications.
____

== Specializing the EFSP

A working group may, through their specification committee, choose to specialize the Eclipse Foundation Specification Process (EFSP) for their own implementation. The process document is a foundational document that defines underlying principles, fundamental rules, and other requirements with regard to implementing specifications. The process document does not generally prescribe the use of specific technology, or provide any detail with regard to implementation. 

This document starts by describing what must not be taken away from the specification process, and concludes with some suggestions of what might be considered for a working group's specialization of the process.

=== Minimum Values

The most critical aspect of the EFSP is the management of Essential Claims as defined by the Eclipse IP Policy. In this regard, the requirement that all committers be covered by an Eclipse Foundation Membership Agreement and Working Group Participation Agreement cannot be relaxed. By extension, the restrictions placed on Participants and Participant Representatives cannot be relaxed in any customization of the process, nor can the ability of a Participant to appoint a Participant Representative be inhibited in any way.

The requirements regarding Scope must not be relaxed. Specifically, the requirements regarding approvals and the requirement that the development work of the project stay with the boundaries defined by the Scope must not be curtailed.

The underlying principles of open source (the so-called “Open Source Rules of Engagement”) may not be curtailed. Specifically, all Specification Projects operate in an open and transparent manner, must follow meritocratic practices to promote individuals to positions of power and authority, and (although not strictly listed as a rule of engagement) operate in a vendor neutral manner.

The powers granted to the Project Leadership Chain by the Eclipse Development Process must not be restricted.

In general, quantities included in the EFSP and EDP can be increased, but not decreased:

* The period of time required to run a simple ballot (e.g. a committer election) must not be less than seven days (It is generally accepted at a week is a reasonable minimum period of time to run a ballot that meets a minimum standard of community inclusion);
* Specification committee approval ballots, and ballots that otherwise that require some sort of legal review must not be less than fourteen days to give adequate time for voting members to consult with their legal teams; and
* Specification Teams must engage in at least one Progress Review during the development cycle of a Major or Minor Release (Progress Reviews are not required for Service Releases).

=== Specializing the Process

The EFSP defines a set of underlying principles and fundamental requirements. It intentionally does not define any sort of practical implementation, or prescribe any specific technologies. Specializations of the process should take a similar approach. The process might, for example, extend the amount of time required for a specification committee ballot; but any attempt to describe the specific mechanisms and technology by which a ballet is run in a practical sense is more of an operational detail that should be defined in an operations document.

==== Example Process Specializations

Providing a comprehensive list of every possible thing that can be customized is an impossible task. In place of a comprehensive list, we provide a list of examples of things that might be customized and/or tuned.

A customization may extend the list of Open Source Licenses (but many not remove Licenses from the master list).

A customization may define requirements for evolving itself to create future versions of the Working Group-specific specification process.

The process requires that a Specification Project engage in at least one Progress Review. A customization may:

* Require some specific number of additional Progress Reviews;
* Specify a maximum and/or minimum period of time required for Specification Committee approval ballot;
* Specify the period of time that must pass between Reviews; and
* Describe mitigation steps in the event that a review fails.

The process requires that a Specification Project engage in a Release Review. A customization may:

* Specify a maximum and/or minimum period of time required for Specification Committee approval votes;
* Specify the period of time that must pass between the last Progress Review and the Release Review; and
* Describe mitigation steps in the event that the review fails.

A customization may also define:

* Technical namespaces;
* Criteria for designating a release as major, minor, or service; and
* Criteria, requirements, etc. for managing exceptions in a TCK.

While generally considered best practices, a customization may prescribe:

* How a Specification is bundled for dissemination; 
* Specific file formats for documentation; and
* Document structure and style.

The EFSP provides no specific criteria for designating a specification as a profile, nor does it attempt to define “platform”. A specialization may choose to provide definitions or specify the criteria for designating a specification as a profile.

==== Operational Considerations

Specification committees are encouraged to create an operations document that describes how the process is implemented. The evolution of an operations document tends to be organic, based on building consensus within the team instead of relying on a formal approvals process.

Out of convenience, an operations document may repeat information that’s captured in the process; as such, an operations document must include a clear statement that in the event of conflict the process document must be taken as the authority.

The practical implementation of aspects of the process are not defined by the EFSP, and so a Working Group Specification Process (customization) may choose to formalize (for example):

* How to run Specification Committee Ballot;
* How a Participant appoints a Participant Representative;
* What to do when a ballot fails or approval is not otherwise granted;
* The mechanism by which a Specification Committee determines whether or not a minor correction made during a ballot changes semantic meaning;
* How a Specification Version becomes a Final Specification; 
* Requirements/guidelines to pass a Progress Review, along with timing of the review itself; and
* A standard means of describing relationships between specifications.
